apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: recrete-deployment 
  labels: 
    app: myapp
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      app: myapp
  strategy:
    type: Recreate 
  template: 
    metadata: 
      name: my-template 
      labels: 
        app: myapp
    spec: 
      containers: 
        - name: nginx-container
          image: nginx:latest
          ports: 
            - name: mynginxport
              containerPort: 80
